xdp-tools: Upgrade recipe to v1.4.3
Add bpftool native dependency in order to build all utilities,
including xdp-bench xdp-forward xdp-monitor xdp-trafficgen.
Without bpftool suport, only xdp-filter xdp-loader xdp-dump
 were compiled.

Also, fix headers not found because sysroot path not in BPF_CFLAGS:
| xdp_load_bytes.bpf.c:4:10: fatal error: 'bpf/bpf_helpers.h' file not found

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>

diff --git a/meta-intel-distro/dynamic-layers/clang-layer/recipes-support/xdp-tools/xdp-tools/0001-configure-skip-toolchain-checks.patch b/meta-intel-distro/dynamic-layers/clang-layer/recipes-support/xdp-tools/xdp-tools/0001-configure-skip-toolchain-checks.patch
--- a/meta-intel-distro/dynamic-layers/clang-layer/recipes-support/xdp-tools/xdp-tools/0001-configure-skip-toolchain-checks.patch
+++ b/meta-intel-distro/dynamic-layers/clang-layer/recipes-support/xdp-tools/xdp-tools/0001-configure-skip-toolchain-checks.patch
@@ -1,7 +1,7 @@
-From 9c9dce2e5f04de65b7b00321f96fff6071546ea1 Mon Sep 17 00:00:00 2001
+From 076a8e203eec179d1b29459cf6447be0c413659e Mon Sep 17 00:00:00 2001
 From: Naveen Saini <naveen.kumar.saini@intel.com>
 Date: Mon, 17 Oct 2022 15:44:16 +0800
-Subject: [PATCH] configure: skip toolchain checks
+Subject: [PATCH 1/4] configure: skip toolchain checks
 
 Current logic fetch full command line along with the tool. i.e
 gcc -m64 -march=skylake -mtune=generic ...
@@ -14,31 +14,33 @@ environment too.
 Upstream-Status: Inappropriate
 
 Signed-off-by: Naveen Saini <naveen.kumar.saini@intel.com>
-
 ---
  configure | 12 ++++++------
  1 file changed, 6 insertions(+), 6 deletions(-)
 
 diff --git a/configure b/configure
-index b4e824f..10618fc 100755
+index 0c8014d..5ad33fb 100755
 --- a/configure
 +++ b/configure
-@@ -69,12 +69,12 @@ check_toolchain()
+@@ -73,12 +73,12 @@ check_toolchain()
      CLANG=$(find_tool clang "$CLANG")
      LLC=$(find_tool llc "$LLC")
  
--    for TOOL in $PKG_CONFIG $CC $LD $OBJCOPY $CLANG $LLC $M4; do
+-    for TOOL in $PKG_CONFIG $CC $LD $OBJCOPY $CLANG $LLC $M4 $READELF; do
 -        if [ ! $(command -v ${TOOL} 2>/dev/null) ]; then
 -            echo "*** ERROR: Cannot find tool ${TOOL}" ;
 -            exit 1;
 -        fi;
 -    done
-+    #for TOOL in $PKG_CONFIG $CC $LD $OBJCOPY $CLANG $LLC $M4; do
-+    #    if [ ! $(command -v ${TOOL} 2>/dev/null) ]; then
-+    #        echo "*** ERROR: Cannot find tool ${TOOL}" ;
-+    #        exit 1;
-+    #    fi;
-+    #done
++#    for TOOL in $PKG_CONFIG $CC $LD $OBJCOPY $CLANG $LLC $M4 $READELF; do
++#        if [ ! $(command -v ${TOOL} 2>/dev/null) ]; then
++#            echo "*** ERROR: Cannot find tool ${TOOL}" ;
++#            exit 1;
++#        fi;
++#    done
  
-     clang_version=$($CLANG --version | grep -Po '(?<=clang version )[[:digit:]]+')
-     if [ "$?" -ne "0" ]; then
+     ARCH_NAME=$($CC -print-multiarch 2>/dev/null)
+ 
+-- 
+2.25.1
+
